apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rsqxnd7fh-python 
  janus-idp.io/tekton: rsqxnd7fh-python
  backstage.io/kubernetes-id: rsqxnd7fh-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rsqxnd7fh-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml